### ISSUE TITLE
setting supervisorid in create event

### ISSUE THREAD

**Issue by mouki9** [Tools4everBV/HelloID-Conn-Prov-Target-Inception#5]
As discussed with Jerry, in the create event lifecycle we cannot set the supervisorid directly.
In the create event we use a POST method in the endpoint /api/v2/hrm/employees
Whenever supplying the supervisorid we get an error 500 internal server error. 
In the update event we use a PUT method in the endpoint /api/v2/hrm/employees. This does work when we supply the supervisorid. 
In the Inception REST API documentation we see that both options should support the supervisorid.

**Comment by jbreek** [comment]
Builtin workaround for now is added to the code. Within the create, the supervisorid is not set, but is set in the update. When $correlatedAccount=$true, update is followed immediately.
Furthermore there is a check if a managerReference is found and if not present, the manager will be lookup up in Inception directly. This to prevent with initial implementations that managers are not yet correlated.
